require:
  - ../../node_modules/source-map-support/register
  - ../../node_modules/ts-node/register/transpile-only
  - ../../node_modules/should
recursive: true
bail: true
extension:
  - js
  - ts
timeout: 500000
parallel: true
# jobs: 10
