recursive: true
require:
-  ../../node_modules/source-map-support/register
- ../../node_modules/ts-node/register/transpile-only
- ../../node_modules/should
timeout: 20000
extension:
- ts
- js
bail: true
parallel: false